spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hamster-online?usrSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true;characterEncoding=UTF-8
    username: root
    password: 123456
  #  ?? ????? ?????
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss

  main:
    allow-circular-references: true
  configuration:
    mapperLocations: classpath*:/mapper/*Mapper.xml #??Mapper?????? mybatis-plus???? ????mapper??????Mapper.xml
    typeAliasesPackage: com.hamster.entity  #???????? ?????????
    mapUnderscoreToCamelCase: true #??????  mybatis-plus??????  mybatis??????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: status  #???? ??????
      logic-delete-value: 0 #??????  status??0
      logic-not-delete-value: 1 #????? status??1
  thymeleaf:
    cache: false #?????????

pagehelper:
  #?????????
  auto-dialect: mysql
  # 3.3.0???? - ??????????false???
  #?????????pageNum<1?????????pageNum>pages???????
  #?????????pageNum<1?????????pageNum>pages???????
  reasonable: true

  support-methods-arguments: true
  # ???true????pageSize=0??RowBounds.limit = 0??????????
  #??????????????????????Page???
  page-size-zero: true
  #3.5.0???? - ????startPage(Object params)??
  #?????`params`?????????????Map?ServletRequest???
  # ????pageNum,pageSize,count,pageSizeZero,reasonable,??????????
  # ????????????????????
  params: count=countSql
